//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDM_car_w
{
    using System;
    using System.Collections.Generic;
    
    public partial class basket
    {
        public int id { get; set; }
        public Nullable<int> fk_services { get; set; }
        public Nullable<int> fk_client_new { get; set; }
    
        public virtual Client_reserv Client_reserv { get; set; }
        public virtual services services { get; set; }
    }
}
