//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDM_car_w
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Connect : DbContext
    {
        public Connect()
            : base("name=Connect")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<basket> basket { get; set; }
        public virtual DbSet<Client_reserv> Client_reserv { get; set; }
        public virtual DbSet<Date_reserv> Date_reserv { get; set; }
        public virtual DbSet<services> services { get; set; }
    }
}
