//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace travel_company
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model_travel_companyContainer : DbContext
    {
        public Model_travel_companyContainer()
            : base("name=Model_travel_companyContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<trip> tripSet { get; set; }
        public virtual DbSet<customers> customersSet { get; set; }
        public virtual DbSet<travel_agent> travel_agentSet { get; set; }
        public virtual DbSet<client_base> client_baseSet { get; set; }
        public virtual DbSet<Creat_table_baseClient> Creat_table_baseClientSet { get; set; }
    }
}
