//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace travel_company
{
    using System;
    using System.Collections.Generic;
    
    public partial class travel_agent
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string last_name { get; set; }
        public int client_baseId { get; set; }
    
        public virtual client_base client_base { get; set; }
    }
}
